### ISSUE TITLE
I can not accept  the email to activate my account.

### ISSUE THREAD

**Issue by JulyUp** [lalor/todolist#1]
Hello, When I register, I can not accept  the email to activate my account. How to solve this problem?

**Comment by lalor** [comment]
r u chinese ?

This is a unfinished project just for  teaching. you can use `admin` and `admin` to login.

**Comment by JulyUp** [comment]
是的。我是chinese. 现在我也做了一个基于flask的网站，但是没有用户注册登陆等功能。看了miguelgrinberg大神的flasky，但感觉用户管理方面还是很简单。如果想添加别的如实名认证，产品续费什么的功能感觉挺难的。有没有基于flask的具有成熟的用户管理的开源代码？

**Comment by lalor** [comment]
产品续费和实名认证，估计有经验的人不多了，得自己研究……大多数情况用Flask的都是小网站或者内部系统，认证功能都比较简单。

**Comment by JulyUp** [comment]
忧伤。。
