### ISSUE TITLE
我想问一下，这里添加一个list的实现，和修改删除是不是不一样。

### ISSUE THREAD

**Issue by ghost** [lalor/todolist#2]
在html里面我也不会找ADD这个键对应的类是哪个。如果独立写出来应该如何修改呢？与修改删除操作一样吗？目前的代码里，是不是通过请求方式的不同来判断的显示和添加呢？

**Comment by lalor** [comment]
"目前的代码里，是不是通过请求方式的不同来判断的显示和添加"，是的。

如果把添加按钮独立出来，那就是一个新的添加页面。是这个意思吧？
